image: node:7-slim

stages:
- build
- test
- deploy
- docker

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/singuerinc-labs/bi:$CI_BUILD_TAG
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/singuerinc-labs/bi:latest

cache:
  paths:
  - node_modules/

pages:build:
  environment: production
  script:
  - echo "build"
  only:
  - tags

pages:
  environment: production
  stage: deploy
  script:
  - npm i -g yarn
  - yarn
  - yarn run build
  artifacts:
    paths:
    - $CI_PROJECT_DIR/public
  only:
  - tags

pages:push-docker-images:
  image: docker:git
  services:
  - docker:dind
  environment: production
  stage: docker
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t $CONTAINER_TEST_IMAGE .
  - docker push $CONTAINER_TEST_IMAGE
  - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
  - docker push $CONTAINER_RELEASE_IMAGE
  only:
  - tags