image: node:7-slim

stages:
  - deploy

cache:
  paths:
  - node_modules/

pages:
  environment: production
  stage: deploy
  script:
  - npm i -g yarn
  - yarn
  - yarn run build
  artifacts:
    paths:
    - public
  only:
      - master