image: node:7-slim

stages:
- build
- test
- deploy
- docker

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/singuerinc-labs/bi:$CI_BUILD_TAG
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/singuerinc-labs/bi:latest
  
pages:test:
  environment: production
  stage: test
  script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - yarn
  - yarn run test

pages:
  environment: production
  stage: deploy
  script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - yarn
  - yarn run build
  artifacts:
    paths:
    - $CI_PROJECT_DIR/public
  only:
  - tags

pages:push-docker-images:
  environment: production
  stage: docker
  image: docker:git
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t $CONTAINER_TEST_IMAGE .
  - docker push $CONTAINER_TEST_IMAGE
  - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
  - docker push $CONTAINER_RELEASE_IMAGE
  only:
  - tags
