image: node:latest

stages:
- build
- test
- deploy
- docker

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/singuerinc-labs/bi:$CI_BUILD_TAG
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/singuerinc-labs/bi:latest
  
pages:
  environment: production
  stage: deploy
  script:
  - yarn
  - yarn run build
  - sed -i -e "s/\$ACME_FILE_NAME/$ACME_FILE_NAME/" ./acme_file_template
  - sed -i -e "s/\$ACME_FILE_CONTENT/$ACME_FILE_CONTENT/" ./acme_file_template
  - mkdir -p ./public/.well-known/acme-challenge/
  - mv ./acme_file_template ./public/.well-known/acme-challenge/$ACME_FILE_NAME
  artifacts:
    paths:
    - $CI_PROJECT_DIR/public
  only:
  - tags

pages:push-docker-images:
  environment: production
  stage: docker
  image: docker:git
  services:
  - docker:dind
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t $CONTAINER_TEST_IMAGE .
  - docker push $CONTAINER_TEST_IMAGE
  - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
  - docker push $CONTAINER_RELEASE_IMAGE
  only:
  - tags
