version: "2"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: singuerinc-labs/bigstagram
    command: yarn run serve
    volumes:
      - ./:/src/app
    ports:
      - 8080:8080
