version: "2"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: singuerinc-labs/bi
    command: yarn run dev
    stdin_open: true
    tty: true
    volumes:
      - ./:/src/app
    ports:
      - 8080:8080
